/*Myanmar contact*/
insert into contact(type,value,employeeId) values('email','htetaung@yahoo.com',1);
insert into contact(type,value,employeeId) values('homephone','+95-996-555-5662',1);
insert into contact(type,value,employeeId) values('email','linhlaing@yahoo.com',2);
insert into contact(type,value,employeeId) values('homephone','+95-925-555-81',2);
insert into contact(type,value,employeeId) values('email','heinhtet@yahoo.com',3);
insert into contact(type,value,employeeId) values('homephone','+95-965-558-6266',3);
insert into contact(type,value,employeeId) values('email','aungmyint@yahoo.com',4);
insert into contact(type,value,employeeId) values('homephone','+95-944-555-46',4);
insert into contact(type,value,employeeId) values('email','sydneesmith92@yahoo.com',5);
insert into contact(type,value,employeeId) values('skype','oceansindhu',6);

/*Myanmar certificate*/
insert into certificate(name,type,year,employeeId) values('Google Certified Professional Cloud Architect','programing',2018,1);
insert into certificate(name,type,year,employeeId) values('Project Management Professional','management',2010,2);
insert into certificate(name,type,year,employeeId) values('Certified ScrumMater','management',2003,3);
insert into certificate(name,type,year,employeeId) values('AWS Certified Solutions Architect - Associate','programing',2010,10);
insert into certificate(name,type,year,employeeId) values('AWS Certified Developer - Associate','programing',2019,5);
insert into certificate(name,type,year,employeeId) values('Microsoft Certified Solutions Expert (MCSE)','programing',2003,2);
insert into certificate(name,type,year,employeeId) values('ITIL Foundation','programing',2001,3);
insert into certificate(name,type,year,employeeId) values('Certified Information Sercurity Manager (CISM)','programing',2012,4);
insert into certificate(name,type,year,employeeId) values('Certified in Risk and Information Systems Control (CRISC)','programing',2014,9);
insert into certificate(name,type,year,employeeId) values('Certified Information System Sercurity Professional (CISSP)','programing',2016,1);
insert into certificate(name,type,year,employeeId) values('IELTS','language',2017,1);
insert into certificate(name,type,year,employeeId) values('Toeic','language',2011,2);
insert into certificate(name,type,year,employeeId) values('JLPT N5','language',2009,8);
insert into certificate(name,type,year,employeeId) values('JLPT N4','language',2008,4);
insert into certificate(name,type,year,employeeId) values('JLPT N3','language',2005,5);
insert into certificate(name,type,year,employeeId) values('JLPT N2','language',2015,1);
insert into certificate(name,type,year,employeeId) values('JLPT N1','language',2012,2);
insert into certificate(name,type,year,employeeId) values('HSK Basic (1-3)','language',2018,3);
insert into certificate(name,type,year,employeeId) values('HSK Elementary-Intermediate (4-8)','language',2013,4);
insert into certificate(name,type,year,employeeId) values('HSK Advanced (9-11)','language',2015,5);
insert into certificate(name,type,year,employeeId) values('TOPIK-I','language',2020,1);
insert into certificate(name,type,year,employeeId) values('TOPIK-II','language',2017,2);
insert into certificate(name,type,year,employeeId) values('A1 (TEU: elementary level)','language',1993,3);
insert into certificate(name,type,year,employeeId) values('A2 (TBU: basic level)','language',2011,4);
insert into certificate(name,type,year,employeeId) values('B1 (ToRFL-I: the first level)','language',2000,5);
insert into certificate(name,type,year,employeeId) values('B2 (TORFL-II: the second level)','language',2016,1);
insert into certificate(name,type,year,employeeId) values('C1 (TORFL -III: third level)','language',2015,7);
insert into certificate(name,type,year,employeeId) values('C2 (TORFL -IV: fourth level)','language',1999,3);

/*Swizzerland contact*/
insert into contact(type,value,employeeId) values('email','paitynlewis97@yahoo.com',11);
insert into contact(type,value,employeeId) values('homephone','+41-785-559-601',11);
insert into contact(type,value,employeeId) values('email','briannamiller96@yahoo.com',12);
insert into contact(type,value,employeeId) values('homephone','+41-765-551-295',12);
insert into contact(type,value,employeeId) values('email','humbertogreen87@yahoo.com',13);
insert into contact(type,value,employeeId) values('homephone','+41-765-555-781',13);
insert into contact(type,value,employeeId) values('email','deaconwright97@yahoo.com',14);
insert into contact(type,value,employeeId) values('homephone','+41-795-551-227',14);
insert into contact(type,value,employeeId) values('email','sydneesmith92@yahoo.com',15);
insert into contact(type,value,employeeId) values('homephone','+41-795-559-894',15);

/*Swizzerland certificate*/
insert into certificate(name,type,year,employeeId) values('JLPT N2','language',2014,11);
insert into certificate(name,type,year,employeeId) values('JLPT N1','language',2015,12);
insert into certificate(name,type,year,employeeId) values('HSK Basic (1-3)','language',2016,13);
insert into certificate(name,type,year,employeeId) values('HSK Elementary-Intermediate (4-8)','language',2017,14);
insert into certificate(name,type,year,employeeId) values('HSK Advanced (9-11)','language',2018,15);
insert into certificate(name,type,year,employeeId) values('TOPIK-I','language',2015,12);
insert into certificate(name,type,year,employeeId) values('TOPIK-II','language',2014,14);

/*Vietnam contact*/
insert into contact(type,value,employeeId) values('email','cobemuadong@yahoo.com',11);
insert into contact(type,value,employeeId) values('skype','hannahjones67',11);
insert into contact(type,value,employeeId) values('homephone','+84-555-539-425',12);
insert into contact(type,value,employeeId) values('email','atticusrobinson05@yahoo.com',12);
insert into contact(type,value,employeeId) values('skype','atticusrobinson05',13);
insert into contact(type,value,employeeId) values('email','bryanmiller78@yahoo.com',13);
insert into contact(type,value,employeeId) values('skype','joyclark25',14);
insert into contact(type,value,employeeId) values('homephone','+84-555-505-289',14);
insert into contact(type,value,employeeId) values('email','jeramiahcampbell74@yahoo.com',15);
insert into contact(type,value,employeeId) values('email','gavinjohnson25@yahoo.com',15);
insert into contact(type,value,employeeId) values('skype','humbertoevans50',16);
insert into contact(type,value,employeeId) values('homephone','+84-555-537-768',16);
insert into contact(type,value,employeeId) values('email','hunterrobinson36@yahoo.com',17);
insert into contact(type,value,employeeId) values('homephone','+84-855-542-419',17);
insert into contact(type,value,employeeId) values('email','madisonrobinson22@outlook.com',18);
insert into contact(type,value,employeeId) values('homephone','+84-955-559-977',18);
insert into contact(type,value,employeeId) values('email','noelgreen66@yahoo.com',19);
insert into contact(type,value,employeeId) values('homephone','+84-355-549-110',19);
insert into contact(type,value,employeeId) values('skype','juliamartin40',20);
insert into contact(type,value,employeeId) values('homephone','+84-955-568-342',20);
insert into contact(type,value,employeeId) values('email','jamesgarcia53@yahoo.com',21);
insert into contact(type,value,employeeId) values('homephone','+84-355-549-105',21);
insert into contact(type,value,employeeId) values('email','vivianmoore42@outlook.com',22);
insert into contact(type,value,employeeId) values('homephone','+84-755-541-800',22);
insert into contact(type,value,employeeId) values('email','emmyevans16@outlook.com',23);
insert into contact(type,value,employeeId) values('homephone','+84-355-526-313',23);
insert into contact(type,value,employeeId) values('skype','gavinwalker38',24);
insert into contact(type,value,employeeId) values('homephone','+84-955-528-454',24);
insert into contact(type,value,employeeId) values('email','tyresewalker05@outlook.com',25);
insert into contact(type,value,employeeId) values('homephone','+84-755-550-377',25);
insert into contact(type,value,employeeId) values('email','chloegarcia96@outlook.com',26);
insert into contact(type,value,employeeId) values('homephone','+84-555-519-984',26);
insert into contact(type,value,employeeId) values('email','rileycampbell13@yahoo.com',27);
insert into contact(type,value,employeeId) values('homephone','+84-355-586-575',27);
insert into contact(type,value,employeeId) values('email','carterjohnson66@yahoo.com',28);
insert into contact(type,value,employeeId) values('homephone','254374692',28);
insert into contact(type,value,employeeId) values('skype','miamoore04',29);
insert into contact(type,value,employeeId) values('homephone','+84-855-504-976',29);
insert into contact(type,value,employeeId) values('email','aliviaadams15@yahoo.com',30);
insert into contact(type,value,employeeId) values('skype','brooklynroberts53',30);

/*Vietnam certificate*/
insert into certificate(name,type,year,employeeId) values('Google Certified Professional Cloud Architect','programing',1999,23);
insert into certificate(name,type,year,employeeId) values('Project Management Professional','management',2000,20);
insert into certificate(name,type,year,employeeId) values('Certified ScrumMater','management',2001,30);
insert into certificate(name,type,year,employeeId) values('AWS Certified Solutions Architect - Associate','programing',2002,28);
insert into certificate(name,type,year,employeeId) values('AWS Certified Developer - Associate','programing',2003,35);
insert into certificate(name,type,year,employeeId) values('Microsoft Certified Solutions Expert (MCSE)','programing',2004,29);
insert into certificate(name,type,year,employeeId) values('ITIL Foundation','programing',2005,33);
insert into certificate(name,type,year,employeeId) values('Certified Information Sercurity Manager (CISM)','programing',2006,26);
insert into certificate(name,type,year,employeeId) values('Certified in Risk and Information Systems Control (CRISC)','programing',2007,20);
insert into certificate(name,type,year,employeeId) values('Certified Information System Sercurity Professional (CISSP)','programing',2008,31);
insert into certificate(name,type,year,employeeId) values('IELTS','language',2009,35);
insert into certificate(name,type,year,employeeId) values('Toeic','language',2010,30);
insert into certificate(name,type,year,employeeId) values('JLPT N5','language',2011,17);
insert into certificate(name,type,year,employeeId) values('JLPT N4','language',2012,21);
insert into certificate(name,type,year,employeeId) values('JLPT N3','language',2013,27);
insert into certificate(name,type,year,employeeId) values('JLPT N2','language',2014,30);
insert into certificate(name,type,year,employeeId) values('JLPT N1','language',2015,35);
insert into certificate(name,type,year,employeeId) values('HSK Basic (1-3)','language',2016,28);
insert into certificate(name,type,year,employeeId) values('HSK Elementary-Intermediate (4-8)','language',2017,18);
insert into certificate(name,type,year,employeeId) values('HSK Advanced (9-11)','language',2018,17);
insert into certificate(name,type,year,employeeId) values('TOPIK-I','language',2015,16);
insert into certificate(name,type,year,employeeId) values('TOPIK-II','language',2014,22);
insert into certificate(name,type,year,employeeId) values('A1 (TEU: elementary level)','language',2011,30);
insert into certificate(name,type,year,employeeId) values('A2 (TBU: basic level)','language',2010,34);
insert into certificate(name,type,year,employeeId) values('B1 (ToRFL-I: the first level)','language',2008,17);
insert into certificate(name,type,year,employeeId) values('B2 (TORFL-II: the second level)','language',2003,24);
insert into certificate(name,type,year,employeeId) values('C1 (TORFL -III: third level)','language',2017,29);
insert into certificate(name,type,year,employeeId) values('C2 (TORFL -IV: fourth level)','language',2019,31);
